# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "swagger" ]
  pull_request:
    branches: [ "swagger" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ver 18.0.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.0.0
        cache: 'npm'

    - name: CI
      run: npm ci

    - name: Build Swagger Docs
      run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy with Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "maeilmail-api-docs"
          heroku_email: "bjh4135@gmail.com"
   

